import ExcelJS from "exceljs";

export type ParticipantsExportRow = {
  fullName: string;
  email: string;
  eventTitle: string;
  status: string;
  points: number;
};

export type ExportMetadata = {
  generatedAt: string;
  generatedBy: string;
  filters: string;
};

const formulaInjectionPrefix = /^[=+\-@\t\r\n]/;

export function escapeExcelFormula(value: unknown) {
  if (typeof value !== "string") return value;
  return formulaInjectionPrefix.test(value) ? "'" + value : value;
}

function safeRow(row: ParticipantsExportRow) {
  return {
    fullName: escapeExcelFormula(row.fullName),
    email: escapeExcelFormula(row.email),
    eventTitle: escapeExcelFormula(row.eventTitle),
    status: escapeExcelFormula(row.status),
    points: row.points,
  };
}

export async function participantsWorkbook(
  rows: ParticipantsExportRow[],
  metadata: ExportMetadata = {
    generatedAt: new Date().toISOString(),
    generatedBy: "system",
    filters: "all",
  },
) {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = metadata.generatedBy;
  workbook.created = new Date(metadata.generatedAt);

  const meta = workbook.addWorksheet("Export metadata");
  meta.columns = [
    { header: "Field", key: "field", width: 22 },
    { header: "Value", key: "value", width: 56 },
  ];
  meta.addRows([
    { field: "Generated at", value: metadata.generatedAt },
    { field: "Generated by", value: metadata.generatedBy },
    { field: "Filters", value: metadata.filters },
    { field: "Rows", value: rows.length },
  ]);

  const sheet = workbook.addWorksheet("Participants");
  sheet.columns = [
    { header: "Full name", key: "fullName", width: 28 },
    { header: "Email", key: "email", width: 32 },
    { header: "Event", key: "eventTitle", width: 42 },
    { header: "Status", key: "status", width: 18 },
    { header: "BPR points", key: "points", width: 12 },
  ];
  rows.forEach((row) => sheet.addRow(safeRow(row)));

  return workbook.xlsx.writeBuffer();
}
